version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '5056:8080'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
