CREATE TABLE IF NOT EXISTS ADDRESS(
    LINE_1 VARCHAR(255) NOT NULL,
    LINE_2 VARCHAR(255) NOT NULL,
    POSTAL_CODE VARCHAR(15) NOT NULL UNIQUE,
    CITY VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,

    PRIMARY KEY (POSTAL_CODE)
);

