CREATE TABLE IF NOT EXISTS CUSTOMERS(
    NAME VARCHAR(50) NOT NULL,
    DOCUMENT_NUMBER VARCHAR(15) NOT NULL UNIQUE,
    AGE INT NOT NULL,
    ADDRESS_ID VARCHAR(255),
    ACCOUNT_ID INT,

    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(postal_code),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(account_number),

    PRIMARY KEY (DOCUMENT_NUMBER)
);