CREATE TABLE IF NOT EXISTS CREDIT_CARDS(
    CARD_NUMBER VARCHAR(16) NOT NULL UNIQUE,
    CARD_BRAND VARCHAR(50) NOT NULL,
    EXPIRATION_DATE VARCHAR(8) NOT NULL,
    CVV VARCHAR(3),
    CREDIT_LIMIT FLOAT NOT NULL,
    ACCOUNT_ID INT,

    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(account_number),

    PRIMARY KEY (CARD_NUMBER)
);